### PR TITLE
prevent duplicate invocations for aboutToBeReconciled

### PR DESCRIPTION
**Pull request by ibazzi**
Hi Thierry,

first of all this pull request needs to be merged.

Thanks.

### CODE REVIEW

**Comment by ibazzi** [comment]
And the new ASTProvider does not works as expected.

Try the code:

    <?php
    namespace error5\ns1;

    use Exception;

    class Test {

        function function_name(Exception $param) {
        }

    }

Steps:

- cursor on the use statement and `ctrl + d` to delete the line
- `ctrl + shift + o` to trigger organizer (before reconciling finished)
- holding `ctrl + shift + o`, do not release them

and you will get:

    <?php
    namespace error5\ns1;

    use Exception;

    use Exception;

    use Exception;

    use Exception;

    class Test {

        function function_name(Exception $param) {
        }

    }

**Comment by ibazzi** [comment]
I tried again, it seems this pull request cause the issue.

Without this patch, it works well.

**Comment by tbl0605** [comment]
Hi Alex,
I think I will send my patch as-is to gerrit, since it works fine after some days of testing.
Except if you find bugs directly in the new AST* classes of course ;)

I know there is still room for a lot of improvements, for example variable highlighting is still clumsy sometimes (like before, so it's not a regression). Probably other things (like you tried to correct with your patch), but since it's not directly related to the AST* classes better merge them afterwards, so in case of new bugs we can more easily find the culprit between all those changes.

If you made your patch to correct a severe bug in classes PHPStructuredTextViewer and PHPStructuredEditor I can exclude both class updates from my patch if you want.

I think I will send my patch to gerrit tomorrow evening or saturday, I'll test more meanwhile.

Thierry.

**Comment by ibazzi** [comment]
OK, let's improve the rest afterwards

**Comment by tbl0605** [comment]
Yes, btw thank you Alex for taking time to help and review all those ASTProvider&reconcile bugs ;)

**Comment by ibazzi** [comment]
Hi Thierry,

I think about the new AST* class again. I'm not sure if I am right.

As I understand, if `wait_flag = WAIT_YES`, we will get the AST from cache if `STATES = DONE`, otherwise create a new AST from the given ISourceModule.

Now here is the problem.

Currently, `PHPStructuredEditor.aboutToBeReconciled()` will be called all the time when we typing. I think this is not correct. So my patch avoid this. 

After my patch, `aboutToBeReconciled` only called once before the reconciler finished the reconciling progress.(`ASTCache.reset()` will be called only once)

So when trigger multiple `ctrl + shift +o`(`wait_flag = WAIT_YES`), we always get the old AST from the new created AST(not the reconciled one set by `PHPReconcilingStrategy`), because `ASTCache.reconciled` has not been called. And ASTCache will not WAIT for `ASTCache.reconciled` been called even if the `wait_flag = WAIT_YES`.

I‘m not sure if I have described clearly.

Let me know if you have any question :)

**Comment by ibazzi** [comment]
In my opinion, `WAIT_YES` should always wait for `reconciled` being called.

**Comment by tbl0605** [comment]
Hi Alex,
actually WAIT_YES just means that we :
- retrieve current AST if not null
- generate a new AST if current AST is null
- wait if an AST is under construction and return it when done (assuming it's not null of course, otherwise it means generation went wrong)

There is absolutely no constraint with WAIT_YES that any cached AST must be up-to-date.
That's why we must call aboutToBeReconciled() to reset cache and force a new AST generation for the WAIT_FLAG if we absolutely need an up-to-date AST.
It should be done by callers, using an aboutToBeReconciled() / reconciled() logic.
The WAIT_* flags logic is actually pretty simple (and should stay so), all hard work must be done by its callers ;)

Even so, you will never be 100% sure to work with an up-to-dated AST, because everything is done asynchronously.
Speaking about that, I sometimes get ArrayIndexOutOfBoundsException with SelectionListenerWithASTManager, SemanticHighlightingReconciler or PHPOutlineContentProvider because we probably work with an outdated AST or maybe because we don't correctly check that underlying document is "dirty" or in a reconciliation process.

My plan (again when I have some time) was to look how JDT handles that.
Probably what we miss in PDT is to always ensure that underlying document/source module hasn't changed while working with an AST, the fix is maybe easier that we think ;)

**Comment by ibazzi** [comment]
Yes, So I think if we have called aboutToBeReconciled(), and the flag is WAIT_YES, we must wait until reconciled is called.

I read the ASTProvicer source of JDT, it seems has the same logic.

**Comment by ibazzi** [comment]
Would you like to see this patch if you have some time?
https://github.com/ibazzi/pdt/commit/0d8b487af3db45501d057a5bf9e63002585a265a

This will fix the issue I mentioned above.

**Comment by tbl0605** [comment]
Hi Alex,
I've looked your patch and now I understand better what you mean.
I made myself a patch : https://git.eclipse.org/r/#/c/99986/
I haven't test it yet, could you try it to see if it solves your problem?
Your patch has the disadvantage to re-introduce potential infinite recursive loop, better avoid that :)

**Pull request closed without merging**
